### ISSUE TITLE
Does this check if the renderer part is being executed in a regular browser?

### ISSUE THREAD

**Issue by michaeljota** [delvedor/electron-is#3]
I have not try this, but I'm already using this one [is-electron-renderer](https://github.com/jprichardson/is-electron-renderer).

However, this have the issue that does not distinguish between renderer process and a browser process, properly webpacked. See [this](https://github.com/jprichardson/is-electron-renderer/pull/4)

I would like to know if this support this kind of distinction. 

Thanks! :).

**Comment by delvedor** [comment]
Just to be clear, you have one codebase that works in a standard browser and inside electron, right?

If so, at the moment `electron-is` can define only if you are in the *main/renderer* process and not in a standard browser, this because is an electron library ;)

I don't think can be useful implement this function because is an edge case.
What I can suggest you is to create a function to test the presence of the window object.
For example
```javascript
function isStandardBrowser () {
  try {
    return !!window
  } catch (e) {
    return false
  }
}
// then
if (is.renderer() || isStandardBrowser()) { ... }
```
An this should work.
But pay attention, the `process` object does not exist in a standard browser, then basically all `electron-is` will not work correctly.

**Comment by michaeljota** [comment]
I added previously the process object through `webpack`. Thanks! I'll try this and comment. 😃

**Comment by michaeljota** [comment]
FYI: (Or anyone that end up here).

I did the is.standardBrowser() and it worked. BUT. This is a big but, like **BUT** it didn't matter. 
I wanted to use it to require Electron only if this was executed in the renderer process. but it does not. So, kind of waste of time.

Thanks you. Maybe you want to warn me, but I did not read well.
